"""add country field

Revision ID: 288b1177a412
Revises: d044f0a90c3f
Create Date: 2020-04-28 14:04:50.968134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288b1177a412'
down_revision = 'd044f0a90c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('country', sa.String(), nullable=True))
    op.create_index(op.f('ix_film_country'), 'film', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_film_country'), table_name='film')
    op.drop_column('film', 'country')
    # ### end Alembic commands ###
