"""add rating

Revision ID: 387e80a84078
Revises: 288b1177a412
Create Date: 2020-05-01 14:55:25.880711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387e80a84078'
down_revision = '288b1177a412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('rating', sa.String(), nullable=True))
    op.create_index(op.f('ix_film_rating'), 'film', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_film_rating'), table_name='film')
    op.drop_column('film', 'rating')
    # ### end Alembic commands ###
