"""datetime

Revision ID: 45689cf7c965
Revises: c1be0e510f5f
Create Date: 2020-06-14 13:14:33.060249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45689cf7c965'
down_revision = 'c1be0e510f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('published', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'published')
    # ### end Alembic commands ###
