"""alternative_name

Revision ID: 513821fc0c70
Revises: d74c2cdf4ed8
Create Date: 2020-11-10 20:58:31.879885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513821fc0c70'
down_revision = 'd74c2cdf4ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('alternative_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_film_alternative_name'), 'film', ['alternative_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_film_alternative_name'), table_name='film')
    op.drop_column('film', 'alternative_name')
    # ### end Alembic commands ###
