"""Serial migrate.

Revision ID: 9bf8e66f3165
Revises: 513821fc0c70
Create Date: 2020-12-09 21:51:57.320965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf8e66f3165'
down_revision = '513821fc0c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_lower', sa.String(), nullable=True),
    sa.Column('alternative_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('kino_id', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('producer', sa.String(), nullable=True),
    sa.Column('film_page', sa.String(), nullable=True),
    sa.Column('actors', sa.String(), nullable=True),
    sa.Column('writers', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('music_author', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serial_actors'), 'serial', ['actors'], unique=False)
    op.create_index(op.f('ix_serial_alternative_name'), 'serial', ['alternative_name'], unique=False)
    op.create_index(op.f('ix_serial_category'), 'serial', ['category'], unique=False)
    op.create_index(op.f('ix_serial_country'), 'serial', ['country'], unique=False)
    op.create_index(op.f('ix_serial_img'), 'serial', ['img'], unique=False)
    op.create_index(op.f('ix_serial_kino_id'), 'serial', ['kino_id'], unique=True)
    op.create_index(op.f('ix_serial_music_author'), 'serial', ['music_author'], unique=False)
    op.create_index(op.f('ix_serial_name'), 'serial', ['name'], unique=False)
    op.create_index(op.f('ix_serial_name_lower'), 'serial', ['name_lower'], unique=False)
    op.create_index(op.f('ix_serial_operator'), 'serial', ['operator'], unique=False)
    op.create_index(op.f('ix_serial_producer'), 'serial', ['producer'], unique=False)
    op.create_index(op.f('ix_serial_rating'), 'serial', ['rating'], unique=False)
    op.create_index(op.f('ix_serial_tags'), 'serial', ['tags'], unique=False)
    op.create_index(op.f('ix_serial_writers'), 'serial', ['writers'], unique=False)
    op.create_index(op.f('ix_serial_year'), 'serial', ['year'], unique=False)
    op.drop_index('ix_serials_actors', table_name='serials')
    op.drop_index('ix_serials_category', table_name='serials')
    op.drop_index('ix_serials_country', table_name='serials')
    op.drop_index('ix_serials_img', table_name='serials')
    op.drop_index('ix_serials_kino_id', table_name='serials')
    op.drop_index('ix_serials_music_author', table_name='serials')
    op.drop_index('ix_serials_name', table_name='serials')
    op.drop_index('ix_serials_name_lower', table_name='serials')
    op.drop_index('ix_serials_operator', table_name='serials')
    op.drop_index('ix_serials_producer', table_name='serials')
    op.drop_index('ix_serials_rating', table_name='serials')
    op.drop_index('ix_serials_tags', table_name='serials')
    op.drop_index('ix_serials_writers', table_name='serials')
    op.drop_index('ix_serials_year', table_name='serials')
    op.drop_table('serials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('published', sa.DATETIME(), nullable=True),
    sa.Column('year', sa.VARCHAR(), nullable=True),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('name_lower', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('tags', sa.VARCHAR(), nullable=True),
    sa.Column('kino_id', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('producer', sa.VARCHAR(), nullable=True),
    sa.Column('film_page', sa.VARCHAR(), nullable=True),
    sa.Column('actors', sa.VARCHAR(), nullable=True),
    sa.Column('writers', sa.VARCHAR(), nullable=True),
    sa.Column('operator', sa.VARCHAR(), nullable=True),
    sa.Column('music_author', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('rating', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_serials_year', 'serials', ['year'], unique=False)
    op.create_index('ix_serials_writers', 'serials', ['writers'], unique=False)
    op.create_index('ix_serials_tags', 'serials', ['tags'], unique=False)
    op.create_index('ix_serials_rating', 'serials', ['rating'], unique=False)
    op.create_index('ix_serials_producer', 'serials', ['producer'], unique=False)
    op.create_index('ix_serials_operator', 'serials', ['operator'], unique=False)
    op.create_index('ix_serials_name_lower', 'serials', ['name_lower'], unique=False)
    op.create_index('ix_serials_name', 'serials', ['name'], unique=False)
    op.create_index('ix_serials_music_author', 'serials', ['music_author'], unique=False)
    op.create_index('ix_serials_kino_id', 'serials', ['kino_id'], unique=1)
    op.create_index('ix_serials_img', 'serials', ['img'], unique=False)
    op.create_index('ix_serials_country', 'serials', ['country'], unique=False)
    op.create_index('ix_serials_category', 'serials', ['category'], unique=False)
    op.create_index('ix_serials_actors', 'serials', ['actors'], unique=False)
    op.drop_index(op.f('ix_serial_year'), table_name='serial')
    op.drop_index(op.f('ix_serial_writers'), table_name='serial')
    op.drop_index(op.f('ix_serial_tags'), table_name='serial')
    op.drop_index(op.f('ix_serial_rating'), table_name='serial')
    op.drop_index(op.f('ix_serial_producer'), table_name='serial')
    op.drop_index(op.f('ix_serial_operator'), table_name='serial')
    op.drop_index(op.f('ix_serial_name_lower'), table_name='serial')
    op.drop_index(op.f('ix_serial_name'), table_name='serial')
    op.drop_index(op.f('ix_serial_music_author'), table_name='serial')
    op.drop_index(op.f('ix_serial_kino_id'), table_name='serial')
    op.drop_index(op.f('ix_serial_img'), table_name='serial')
    op.drop_index(op.f('ix_serial_country'), table_name='serial')
    op.drop_index(op.f('ix_serial_category'), table_name='serial')
    op.drop_index(op.f('ix_serial_alternative_name'), table_name='serial')
    op.drop_index(op.f('ix_serial_actors'), table_name='serial')
    op.drop_table('serial')
    # ### end Alembic commands ###
