"""new field name_lower

Revision ID: c1be0e510f5f
Revises: 387e80a84078
Create Date: 2020-05-02 20:19:52.260958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1be0e510f5f'
down_revision = '387e80a84078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('name_lower', sa.String(), nullable=True))
    op.create_index(op.f('ix_film_name_lower'), 'film', ['name_lower'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_film_name_lower'), table_name='film')
    op.drop_column('film', 'name_lower')
    # ### end Alembic commands ###
